import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Josefin_Sans } from "next/font/google";

const josephin_sans = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-josephin-sans",
  weight: ["700", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body className={josephin_sans.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}

//<body className={inter.className}>{children}</body>
